version: "3.8"

services:
  backend-go:
    container_name: backend-golang
    depends_on:
      - db
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    restart: unless-stopped

  db:
    image: postgres:14.0-alpine
    container_name: db-postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres-backend-go:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    ports:
      - "5050:80"
    restart: unless-stopped
    logging:
      driver: none

volumes:
  postgres-backend-go:
